Feature Caixa
mercadolibre/card-form-ios pull request #35
Opened 2020-04-30 12:18 UTC by eboffa

2020-04-30 12:57 UTC, ericertlMELI requested changes

2020-04-30 12:57 UTC, ericertlMELI commented on Source/UI/Controllers/MLCardFormViewController.swift
> +            } else if newValue.count >= 7, let seventhDigit = newValue.prefix(7).last,
Si querias solo el 7mo, podias usar `newValue[6]` o `String(newValue[6])` envez de usar prefix y despues buscar el ultimo

2020-04-30 12:57 UTC, ericertlMELI commented on Source/UI/Controllers/MLCardFormViewController.swift
> +                    if let cardNumberFieldProperty = from.property as? CardNumberFormFieldProperty {
`let cardNumberFieldProperty = from.property as? CardNumberFormFieldProperty` puede ir con las validaciones del if anterior, para no meter un if extra

2020-04-30 12:57 UTC, ericertlMELI commented on Source/UI/Controllers/MLCardFormViewController.swift
> +                            cardNumberFieldProperty.isValid = false
no me convence que esto este aca. Deberia ir en la func de isValid de CardNumberFormField

2020-04-30 12:57 UTC, ericertlMELI commented on Source/ViewModel/FieldProperty/CardNumberFormFieldProperty.swift
> +    enum Validation: String {
Todo este enum para tener un string que se usa en 1 solo lugar? No tiene sentido.

2020-04-30 12:57 UTC, ericertlMELI commented on Source/ViewModel/FieldProperty/CardNumberFormFieldProperty.swift
> +class CardNumberFormFieldProperty : MLCardFormFieldPropertyProtocol {
La idea era que se mantenga todo como structs. Pasa la validacion del 7mo digito aca

2020-04-30 13:03 UTC, eboffa commented on Source/UI/Controllers/MLCardFormViewController.swift
> +            } else if newValue.count >= 7, let seventhDigit = newValue.prefix(7).last,
newValue[6] da el sig error -> 'subscript(_:)' is unavailable: cannot subscript String with an Int

2020-04-30 13:05 UTC, eboffa commented on Source/ViewModel/FieldProperty/CardNumberFormFieldProperty.swift
> +    enum Validation: String {
Ahora viene una sola validación, pero pueden venir más. Por eso de backend nos viene un array de validaciones

2020-04-30 13:07 UTC, eboffa commented on Source/UI/Controllers/MLCardFormViewController.swift
> +                    if let cardNumberFieldProperty = from.property as? CardNumberFormFieldProperty {
Ya esta

2020-04-30 13:10 UTC, eboffa commented on Source/UI/Controllers/MLCardFormViewController.swift
> +                            cardNumberFieldProperty.isValid = false
Si lo paso a la func isValid no tengo manera de mostrar el mensaje de error cuando se ingresa el 7mo digito

2020-04-30 13:11 UTC, eboffa commented on Source/ViewModel/FieldProperty/CardNumberFormFieldProperty.swift
> +    enum Validation: String {
Sino saco el enum y se hace el día que venga una segunda validación

2020-04-30 13:14 UTC, ericertlMELI commented on Source/UI/Controllers/MLCardFormViewController.swift
> +            } else if newValue.count >= 7, let seventhDigit = newValue.prefix(7).last,
ok, pense que teniamos swift 5

2020-04-30 13:21 UTC, ericertlMELI commented on Source/UI/Controllers/MLCardFormViewController.swift
> +                            cardNumberFieldProperty.isValid = false
si, llamas a la func isvalid de CardNumberFormField deberia mostrarlo

2020-04-30 15:18 UTC, ericertlMELI approved these changes
Hay cosas que quedaron raras, hay que revisarlas

2020-05-04 13:58 UTC, ericertlMELI requested changes
Espectacular. Lo unico que te voy a decir que cambies es el protocolo nuevo que armaste. Pasa el metodo a MLCardFormFieldPropertyProtocol y deja una implementacion default en la extension para no romper los otros fields.

2020-05-04 17:52 UTC, ericertlMELI approved these changes

2020-05-07 14:06 UTC, ericertlMELI approved these changes

2020-05-07 14:06 UTC, ericertlMELI commented on Source/Model/BinData/MLCardFormFieldSetting.swift
> +            let validationMessage: String = cardUI.extraValidations?.first?.errorMessage ?? "Completa este campo".localized
Ya que es un array, trataqria de obtener el correcto aca, tipo:

extraValidations.first(where: { $0.name == SEVENTH_DIGIT })

2020-05-07 16:09 UTC, merged